### ISSUE TITLE
Add option to rename ZFS filesystem

### ISSUE THREAD

**Issue by zdykstra** [zdykstra/zfsbootmenu#17]
After cloning a snapshot, the name of the filesystem can get quite huge.

`trident/ROOT/initial_pre-update-2020-02-01-18-44_000_pre-update-2020-02-03-08-37_000_pre-update-2020-02-03-14-48_001@pre-update-2020-02-03-20-14`

An option should exist to easily rename a given filesystem to a new name.

**Comment by zdykstra** [comment]
The technique used in https://github.com/zdykstra/zfsbootmenu/pull/28 can be applied here. read, in readline mode can pre-populate the input section and make this easier. The pool will have to run through the read-only check gate, which likely needs to be pushed to a dedicated function.

**Comment by ahesford** [comment]
This is less compelling after the changes in #40, but might still be useful.

**Comment by zdykstra** [comment]
With the recent improvements in snapshot cloning and duplication, this is effectively not needed.
