### ISSUE TITLE
[FEATURE REQUEST] Support for Ubuntu

### ISSUE THREAD

**Issue by emk2203** [zdykstra/zfsbootmenu#2]
Please add support for Ubuntu as well. Starting from 19.04, the installer is able to install Ubuntu with zfs-on-root. Assuming that this is the canonical way, the standard for Ubuntu should be:

>If your system does NOT use Dracut, I'll be happy to add support. Please open an issue with the following information:

Dracut is not used, Ubuntu/Debian relies on initramfs-tools instead.

>How to detect your OS based on a file in your imported OS pool (contents of /etc/os-release would be a good start).

`cat /etc/os-release`

```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu Focal Fossa (development branch)"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
>How to format the kernel command line for ZFS on your system

Boot stanza from the grub menu, autogenerated by the 10_linux_zfs GRUB file:

```
setparams 'Ubuntu Focal Fossa (development branch)'
        
        recordfail
        load_video
        gfxmode ${linux_gfxmode}
        insmod gzio
        if [ "${grub_platform}" = xen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod zfs
        set root='hd0,gpt4'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs=uuid --set=root --hint-bios=hd0,gpt4 --hint-efi=hd0,gpt4 --hint-baremetal=ahci0,gpt4 afa2440c1b0c14f5
        else
          search --no-floppy --fs=uuid --set=root afa2440c1b0c14f5
        fi
        linux        /BOOT/ubuntu_utwd0l@/vmlinuz-5.3.0-18-generic root=ZFS=rpool/ROOT/ubuntu_utwd0l ro  quiet splash ${vt_handoff}
        initrd        /BOOT/ubuntu_utwd0l@/initrd.img-5.3.0-18-generic
```

>Where you store your default kernel command line parameters.

`/etc/default/grub`

**Comment by zdykstra** [comment]
Thanks for the detailed information. I remembered reading that Ubuntu uses two pools, one for /boot and one for the OS itself. Unfortunately, Ubuntu's design is completely different to how traditional Solaris and FreeBSD BE's are setup, and subsequently how standard Linux BE's are configured. The assumption is that /boot lives in the same pool as the OS, under the filesystem that mounts to /. When this assumption isn't met, a lot of logic needs to be added to figure out where the correct /boot filesystem lives relative to the detected environments.

It's possible that I can add in support for how Ubuntu 20.04 and beyond will configure the system, but it's unfortunately not a priority for me right now. It will take a considerable amount of code to handle their extremely complex/fragile layout. 

I will leave this open as a reminder. Once 20.04 is released and their pool layouts are stable, I can consider adding in support. Thanks!

**Comment by zdykstra** [comment]
After thinking about this issue, I've decided that I'm not going to pursue adding Ubuntu support. Their BE's are closely coupled with Grub, and are not particularly friendly to decipher.
