### ISSUE TITLE
cat: /tmp/zfs.lWmn/obarun/ROOT/master/kernels: No such file or directory

### ISSUE THREAD

**Issue by Yann-Kaelig** [zdykstra/zfsbootmenu#22]
Hi

I'm trying to make zfsbootmenu to work on Obarun (Arch)  but I have some problems.
I can boot and get the Refind menu: 

![](https://i.ibb.co/wCRpY5h/Obarun-ZFSBootmenu-01.png)

By pressing F2 I get this information:

![](https://i.ibb.co/sQT4ZPN/Screenshot-20200228-031303.png)

Then I get the zfsbootmenu:

![](https://i.ibb.co/jMcVK2W/Obarun-ZFSBootmenu-04.png)

First observation when I press ALT+K, the zfsbootmenu is empty:

![](https://i.ibb.co/sm7Zgbd/Obarun-ZFSBootmenu-05.png)

When I press [ENTER] in this menu, this is what is displayed at the bottom of the screen:

![](https://i.ibb.co/QbcDnWp/Screenshot-20200228-010336.png)

Finally at the main menu when I press enter, I get this error:

![](https://i.ibb.co/8jb2fBy/Obarun-ZFSBootmenu-06.png)

My configuration files are available as attached files.

[config.ini.txt](https://github.com/zdykstra/zfsbootmenu/files/4264898/config.ini.txt)
[zfsbootmenu.conf.txt](https://github.com/zdykstra/zfsbootmenu/files/4264899/zfsbootmenu.conf.txt)
[refind_linux.conf.txt](https://github.com/zdykstra/zfsbootmenu/files/4264900/refind_linux.conf.txt)
[fstab.txt](https://github.com/zdykstra/zfsbootmenu/files/4264901/fstab.txt)
[tree-boot.txt](https://github.com/zdykstra/zfsbootmenu/files/4264902/tree-boot.txt)

Thank you
Best Regards

**Comment by zdykstra** [comment]
Thank you for the very detailed bug report, as well as your messages on IRC. I'll see what I can come up with to make this more compatible with your Arch/Obarun.

**Comment by Yann-Kaelig** [comment]
Thank you.
Well, if you are interested to test ZFSBootmenu on Obarun, I can send you the appropriate link to download the virtual drive, vdi file which can be used with virtualbox. I am fully available for this purpose on IRC.

**Comment by zdykstra** [comment]
I believe this issue has been addressed in the release of ZFSBootMenu 1.3, with specific support for Arch-style kernel and initramfs names.
