### ISSUE TITLE
[FEATURE REQUEST] Forward command-line arguments to "client" kernels

### ISSUE THREAD

**Issue by ahesford** [zdykstra/zfsbootmenu#23]
Currently, zfsbootmenu looks in `/etc/default/grub` to find the command-line arguments it passes to "client" kernels it will boot. It might be more convenient and more transparent to forward the arguments passed to the zfsbootmenu kernel. This allows users to specify arguments in the "natural" place: the boot manager that would boot their kernels if zfsbootmenu were not used.

There are a couple of considerations here:
1. Some arguments will need to be culled or replaced when passing to clients (*e.g.*, `zfsbootmenu` or `root` arguments);
2. If zfsbootmenu is using a different kernel version than the one selected for booting, the arguments may not be directly compatible.

The first point may not be that big a deal, because zfsbootmenu already takes responsibility for the `root` argument and removing the specific `zfsbootmenu` argument would be trivial. The second point may be more problematic, since a key feature of boot environments is the booting of different kernel versions. This admits the possibility that the zfsbootmenu and client kernels will have different versions and potentially different sets of supported arguments.

**Comment by zdykstra** [comment]
Work has been started on this in [issue-23](https://github.com/zdykstra/zfsbootmenu/tree/issue-23) . I'm planning on gating this behind `inherit_cmdline=1` on the kernel command line. I'll plan on stripping out `root=*`, `zfsbootmenu=*`, `initrd=*` and `initramfs=*`. I'm not sure if there are any others that can be removed automatically.

**Comment by ahesford** [comment]
With the upcoming move to the `org.zfsbootmenu:commandline` property, I no longer think forwarding command-line arguments from zfsbootmenu "client" kernels is a particularly interesting feature.
