### ISSUE TITLE
liunuxx64.efi.stub part of systemd on Arch

### ISSUE THREAD

**Issue by ashb** [zdykstra/zfsbootmenu#25]
I'm aware that Arch is probably not going to work yet, but I'm trying a few things.

(I've manually made versioned kernel files to get this far)

The objcopy command fails because on Arch linuxx64.efi.stub is part of systemd now, and lives under /usr/lib/systemd/boot/efi/linuxx64.efi.stub

**Comment by ashb** [comment]
Related to #7

**Comment by zdykstra** [comment]
I've pushed a fix for this in https://github.com/zdykstra/zfsbootmenu/commit/931051d9a1963cd68ac3956fad90aec30331cc28 - can you test and let me know if this works? You'll just need to define `Stub=/usr/lib/systemd/boot/efi/linuxx64.efi.stub` in config.ini.

**Comment by ashb** [comment]
Yup, that fixes it.
