### ISSUE TITLE
Failed to boot with "unary operator expected" error.

### ISSUE THREAD

**Issue by ashb** [zdykstra/zfsbootmenu#26]
Line 25 of zfsbootmenu.sh has this:

```
if [ ${rootok} -eq 1 ]; then
  modprobe zfs 2>/dev/null
  udevadm settle
fi
```

Upon trying to boot the menu image I got it complaining about "-eq: unary operator expected" which implies that rootok was unset.

**Comment by zdykstra** [comment]
Thank you for the bug report. Can you let me know a few details about your setup:

* How are you creating the initramfs?
* What is your kernel command line when booting the initramfs?

I've relaxed the check in https://github.com/zdykstra/zfsbootmenu/commit/b4d0c22850f3954c1bbd28a209785532174a61c0 and set it to always attempt to modprobe zfs / settle udev. I expect that this won't fix things entirely for you, but we can at least get a bit further.

**Comment by ashb** [comment]
I didn't explicitly set a cmdline for the zfsbootmenu image. Perhaps that was the problem...

**Comment by zdykstra** [comment]
We now explicitly force the modprobe and udev settle, regardless of rootok being set
