### ISSUE TITLE
First install tutorial

### ISSUE THREAD

**Issue by h-2** [zdykstra/zfsbootmenu#27]
Hey, I am coming from FreeBSD and OpenBSD and I would like to install VoidLinux on my Laptop with ZFS-encrypted home and unencrypted rest.
My Linux knowledge is quite rusty but I had hoped to find a good SystemD-free setup that is ZFS friendly with VoidLinux and your bootmenu! But so far I can't get the system setup. The multitude of configuration options and different bootloaders etc. is quite daunting when one is used to *BSD.

I tried to follow https://github.com/nightah/void-install but things broke once I encrypted the /home -- I wanted to add zfsbootmenu after the install.
It seems like the whole partitioning has to happen differently, though...
Could you tell me which steps to adapt to get zfsbootmenu (and probably rEFInd?) setup directly? If it works, I could try to integrate it with above tutorial as a wiki page in this repository.

Thank you so much!

**Comment by zdykstra** [comment]
The closest guide I have is https://github.com/zdykstra/zfsbootmenu/blob/master/void-install.md - it makes the assumption that you'll put the EFI partition on a USB drive. It's fairly easy to adapt the directions though to make a 500MB EFI partition on the internal drive, and then use the rest of the drive for ZFS.  

However, I'd highly recommend taking a look at https://project-trident.org/ . They've tightly integrated zfsbootmenu into their installer, which does all of the disk setup/configuration for you. It also by-default encrypts your home directory for you.

**Comment by h-2** [comment]
> However, I'd highly recommend taking a look at https://project-trident.org/ . They've tightly integrated zfsbootmenu into their installer, which does all of the disk setup/configuration for you. It also by-default encrypts your home directory for you.

Wow, this is really cool. Thanks for the link, it does more or less exactly what I need!
