### ISSUE TITLE
Failure in Unified UEFI mode isn't propagated

### ISSUE THREAD

**Issue by ericonr** [zdykstra/zfsbootmenu#33]
If the user doesn't install gummiboot, the `objcopy` command fails, but the error isn't propagated. This results in xbps reporting "zfsbootmenu: configured successfully", which is false.

EDIT: That might be an issue with objcopy itself, seems like you included error checking.

**Comment by zdykstra** [comment]
https://github.com/zdykstra/zfsbootmenu/commit/fee1c0d87eb675556b8126a32e4ccf1d4de0daf8

This should take care of it, I'll test when I can get to an x86 system.
