### ISSUE TITLE
Support different command lines with Secure Boot

### ISSUE THREAD

**Issue by ericonr** [zdykstra/zfsbootmenu#37]
Currently, only the UEFI bundle supports Secure Boot. Since the kernel command line is embedded into the generated image,  I would need multiple images generated by zfsbootmenu, one for each variation of the command line. This is interesting because the command line used to boot the can only be one of the pre-configured ones.

The other option is to support signing the kernel itself, and then selecting the boot entry with the normal rEFInd procedure. This is cool, because it has flexibility, but it's not ideal for the security minded, since it allows one to edit the kernel command line to do god knows what.

Therefore, I think it would make sense to enable both of the options, instead of choosing one of them. For the first one, we'd need to find some way of conditionally defining the kernel command line (I suggest setting global variables when running dracut, and then defining the cmdline based on that). For the second one, we could drive `sbsign` manually or wait for `sbctl` release + integration.

**Comment by ericonr** [comment]
For multiple command lines, something like:

```
BuildOptions="timeout notimeout"
CommandLine-timeout="blabla"
CommandLine-notimeout="blabla2"
```

which generate `vmlinuz-timeout-1.0_1.EFI` and `vmlinuz-notimeout-1.0_1.EFI`.

**Comment by ericonr** [comment]
Just as a note, `sbctl` is likely a way better solution for signing images. We could have a hook for it and everything would be magically signed. No need to implement funky logic in zfsbootmenu.

**Comment by ericonr** [comment]
@ahesford 

Since the YAML was partially (?) triggered by this issue, noting issues with that branch here:

- [ ] `generate-zbm` doesn't check if the config file exists
- [ ] errors in YAML parsing aren't caught, so it spits out a bit of a mess. A dry-run/config-check mode might be interesting.
- [ ] the proposed config file should have a `  ManageImages: false` entry, and its command line is wrong (the one in the README seems correct) (I can do this one, even if it's rather simple)
- [ ] with neither `Kernel.Version` nor `Kernel.Path` set, kernel 5.4.55 was used for the initrams, instead of 5.7.12

**Comment by ahesford** [comment]
We can pick up discussion if the YAML change in #64.

**Comment by ericonr** [comment]
Guess I'm closing this
