### ISSUE TITLE
List of boot environments needs proper refresh after emergency shell

### ISSUE THREAD

**Issue by ahesford** [zdykstra/zfsbootmenu#41]
In the current implementation, a list of boot environments is written to `${BASE}/env` before entering the menu input loop in `zfsbootmenu.sh`. Functions that are expected to alter this list, like `clone_snapshot` and (in the `send-recv` branch for now) `duplicate_snapshot`, modify the list by appending to `${BASE}/env` when new boot environments are created.

If the user drops to an emergency shell with `Alt+R` and renames, creates or deletes BEs manually, `${BASE}/env` will be out of sync with reality. If the generation of `${BASE}/env` is moved to a function, complete with a drop to an emergency shell if no boot environments are found, there are two good possibilities for addressing this issue:
1. Call this function in every iteration of the menu input loop. This might slow things down a bit and is often unnecessary, but the list will always be accurate and there will be no need for `clone_snapshot` or `duplicate_snapshot` to update the list when they add a new boot environment.
2. Leave the `{clone,duplicate}_snapshot` functions to update the list as they do no, and only call the BE-list-update function after entering an emergency shell. This will be more efficient, but might not be the most proper approach for some definition of proper.

**Comment by zdykstra** [comment]
I'm inclined to try the first option and get a feel for added latency while navigating the menus. If it proves to seem a little slow, the function can be called only when leaving something that can possibly make changes (snapshot screen, recovery shell).

People with a small number of boot environments and kernels will be the least impacted by calling it every redraw - while those with a lot of BEs and kernels will be the most impacted.

**Comment by ahesford** [comment]
Addressed on the `rescan` branch in #42.

**Comment by ahesford** [comment]
#42 merged.
