### ISSUE TITLE
Unified UEFI images do not seem to honor kernel cmdline as expected

### ISSUE THREAD

**Issue by ahesford** [zdykstra/zfsbootmenu#46]
When producing a unified UEFI image with `generate-zbm`, the contents of `CommandLine` in the `[Kernel]` section of `/etc/zfsbootmenu/config.ini` are passed as the value for the the `--kernel-cmdline` argument to `dracut`. When the unified image is produced, the command-line arguments can be verified with `lsinitrd /path/to/zbm/image`. Everything seems to be done as expected, except there is a blank argument listed first, *e.g.*,
```
Command line:

rd.vconsole.font=ter-124b
nomodeset
i915.modeset=0
ro
quiet
loglevel=0
```

There is an alternative method for setting the kernel cmdline, by setting the `kernel_cmdline` parameter in a dracut configuration file such as `/etc/zfsbootmenu/dracut.conf.d/cmdline.conf`. When `dracut` runs, it concatenates the values of the `kernel_cmdline` parameter with the `--kernel-cmdline` argument passed by `generate-zbm`. If `kernel_cmdline` is nonempty, then there is no blank argument in the `lsinitrd` output. For example, if `/etc/zfsbootmenu/config.ini` contains `CommandLine=zfsbootmenu ro quiet loglevel=1` and `/etc/zfsbootmenu/dracut.conf.d/cmdline.conf` contains `kernel_cmdline="nomodeset i915.modeset=0"`, then `lsinitrd` will show
```
nomodeset
i915.modeset=0
zfsbootmenu
ro
quiet
loglevel=1
```

Either way, one expects these arguments to be used when the unified UEFI image is booted. However, that does not seem to be the case. For one, even with `quiet loglevel=0`, I see kernel messages flashing on screen before the boot menu starts. For another, if I drop to an emergency shell in zfsbootmenu and look at `cat /proc/cmdline`, I see nothing. The output of `dmesg` shows `Command line: \x01`. Some flags, like `rd.vconsole.font`, are properly respected when zfsbootmenu tries to set console options, but other flags that control driver options are not. I have a suspicion that the cmdline flags for dracut are for overriding or augmenting the cmdline seen by later-stage dracut modules and the subsequent boot process, not for setting the early-boot arguments that control the booting of the initial zbm kernel. Maybe `rEFInd` is the only workable approach for setting the cmdline when UEFI implementations don't support passing arguments directly.

Because @ericonr knows more about dracut and unified UEFI images, I'll pull him into this problem.

**Comment by zdykstra** [comment]
`rEFInd` doesn't honor the embedded kernel command line - it explicitly does not pass that along as a parameter to the kernel that's booting. It only knows how to set it via the `refind_linux.conf` configuration file.

**Comment by ahesford** [comment]
I know. The issue is whether we can get the unified UEFI image to honor the command-line arguments set by dracut when booting without `rEFInd`. For now, it seems that `rEFInd` is the only reliable way to pass command-line arguments to kernels when booting from UEFI.

**Comment by zdykstra** [comment]
> I know. The issue is whether we can get the unified UEFI image to honor the command-line arguments set by dracut when booting without `rEFInd`. For now, it seems that `rEFInd` is the only reliable way to pass command-line arguments to kernels when booting from UEFI.

I misread your final sentences, whoops - I thought you were saying something else about `rEFInd`. Pay no mind to me.

**Comment by ahesford** [comment]
Update: I just tested with `1.2rc1` and can confirm that the kernel is not receiving command-line arguments from the dracut UEFI bundle. From the bundle, I see the following command line:
```
i915.enable_guc=2 timeout=5 rd.vconsole.font=ter-124b i8042.nomux=1 i8042.reset=1 i8042.nopnp=1 i8042.dumbkbd=1 i8042.noaux=1 zfsbootmenu ro quiet loglevel=0
```
When I boot to ZBM, I see these arguments in `/etc/cmdline.d/01-default.conf` but not in the `dmesg` output or in `/proc/cmdline`. From the arguments, I would expect to see a message about loading the `i915` GUC/HUC firmware (from `i915.enable_guc=2`) and I would also expect *not* to see the following message that currently appears in my `dmesg` log:
```
i8042: PNP: PS/2 appears to have AUX port disabled, if this is incorrect please boot with i8042.nopnp
```
Note that booting the final image with the same arguments, or booting ZBM with rEFInd passing the arguments, I see expected behavior:
```
i915 0000:00:02.0: HuC firmware i915/kbl_huc_4.0.0.bin version 4.0 authenticated:yes
```
and
```
i8042: PNP detection disabled
```
If we can't figure out why these arguments aren't being passed to the kernel in the UEFI bundle, we are stuck with either rEFInd or a UEFI firmware that properly passes command-line arguments without the need for a bundle.

**Comment by ahesford** [comment]
While I still believe this is an issue, I don't know how reproducible this is and believe it to be an upstream `dracut` or `objcopy` issue if anything.

I'll close this and reopen if I believe that there's something we can do here to overcome the problem.
