### ISSUE TITLE
Kernel version selector should have "set default" abilities

### ISSUE THREAD

**Issue by ahesford** [zdykstra/zfsbootmenu#47]
In the kernel selection menu invoked by `ALT+K` for a specific boot environment, there should be an `ALT+D` hotkey that pins the default kernel version for that environment, much like `ALT+D` at the top level sets a default boot environment. This amounts to setting the pool writable and setting the `org.zfsbootmenu:kernel` property on the current boot environment.

**Comment by zdykstra** [comment]
I can tackle this tonight, unless you have designs on it.

**Comment by ahesford** [comment]
Go ahead; I have nothing started.

**Comment by zdykstra** [comment]
Fixed in #48 !
